name: Java CI

on:
  push:
  pull_request:
    types: [reopened, opened, synchronize]
  schedule:
    - cron:  '30 5 * * *'

jobs:
  test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
        java: [8, 11, 17]
      fail-fast: false
      max-parallel: 1
    name: Test JDK ${{ matrix.java }}, ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v1
      - name: Set up JDK
        uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java }}
      - name: Test with Maven
        env:
          MAVEN_OPTS: "-Xms3g -Xmx5g"
        run: mvn install  -B -V -Pminimal-fix-latest -D"maven.javadoc.skip=true" -D"java.util.logging.config.file"="logging.properties" -D"http.keepAlive"="false" -D"maven.wagon.http.pool"="false" -D"maven.wagon.httpconnectionManager.ttlSeconds"="120"
